-- phpMyAdmin SQL Dump
-- version 4.2.12deb2
-- http://www.phpmyadmin.net
--
-- Client :  localhost
-- Généré le :  Mer 03 Février 2016 à 18:41
-- Version du serveur :  5.6.27-0ubuntu0.15.04.1
-- Version de PHP :  5.6.4-4ubuntu6.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données :  `e_artisan`
--

-- --------------------------------------------------------

--
-- Structure de la table `services`
--

CREATE TABLE IF NOT EXISTS `services` (
`id` int(255) NOT NULL,
  `name` varchar(100) NOT NULL,
  `description` text NOT NULL,
  `publicationDate` datetime NOT NULL,
  `deadline` datetime NOT NULL,
  `status` varchar(20) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8;

--
-- Contenu de la table `services`
--

INSERT INTO `services` (`id`, `name`, `description`, `publicationDate`, `deadline`, `status`) VALUES
(1, 'Alarme & Sécurité', 'J''ai besoin d''un expert en sécurité pour l''installation d''une alarme.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(6, 'Aménagement de cuisine', 'Je vous propose la conception et l''installation de votre cuisine.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(7, 'Aménagement de cuisine', 'J''ai besoin d''une cuisine au plus vite.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(8, 'Aménagement de salle de bains', 'Je suis à votre disposition pour installer votre salle de bains.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(9, 'Aménagement de salle de bains', 'J''ai besoin d''une nouvelle salle de bains !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(10, 'Architecture', 'Architecte depuis 2 mois, je mets mon expertise à votre disposition.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(11, 'Architecture', 'J''ai besoin d''un architecte pour concevoir les plans de ma future maison.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(12, 'Charpenterie', 'Charpentier de formation, je suis prêt à rendre service !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(13, 'Charpenterie', 'Je recherche un charpentier pour ma toiture.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(14, 'Chauffage & Climatisation', 'Je vous propose mes services pour une installation de type chauffage / climatisation.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(15, 'Chauffage & Climatisation', 'J''ai besoin qu''on remplace mon chauffage, et vite !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(16, 'Décoration', 'Je mets ma créativité à votre disposition pour des intérieurs sympas !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(17, 'Décoration', 'Je manque d''inspiration pour ma déco. J''ai besoin de quelqu''un qui s''y connaît !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(18, 'Diagnostic immobilier', 'J''offre un diagnostic immobilier à ceux qui en ont besoin.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(19, 'Diagnostic immobilier', 'Je recherche un expert pour un diagnostic immobilier.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(20, 'Électricité', 'Électricien de formation, j''offre mes services à qui le veut bien !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(21, 'Électricité', 'Mon installation électrique déconne. J''ai besoin d''un électricien rapidement...', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(22, 'Isolation', 'Isolation thermique et phonique, je suis à votre disposition pour un coup de main !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(23, 'Isolation', 'J''ai des pertes de chaleur dans ma maison, j''ai besoin de refaire mon isolation thermique. Quelqu''un pourrait m''aider ?', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(24, 'Maçonnerie', 'Vous voulez construire un mur ? Je suis votre homme !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(25, 'Maçonnerie', 'J''ai besoin d''un maçon rapidement.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(26, 'Menuiserie & Ébénisterie', 'Besoin d''une fenêtre ou d''une porte ? Je mets mon savoir-faire à votre disposition...', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(27, 'Menuiserie & Ébénisterie', 'Je souhaite remplacer toutes mes fenêtres. J''ai besoin d''un menuisier compÃ©tent.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(28, 'Métallerie & Ferronnerie', 'Envie d''un beau portail ou d''une œuvre en métal ? Je suis disponible quand vous le souhaitez.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(29, 'Métallerie & Ferronnerie', 'Je veux remplacer mon portail. Quelqu''un est-il disponible ?', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(30, 'Paysage/Jardin', 'Si vous avez besoin d''un jardinier/paysagiste, je suis à votre écoute !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(31, 'Paysage/Jardin', 'Quelqu''un serait-il disponible pour soigner mon jardin en friche ?', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(32, 'Peinture', 'Je peux repeindre tous vos murs si vous le souhaitez. Contactez-moi !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(33, 'Peinture', 'J''ai besoin d''un peintre en bâtiment pour repeindre ma chambre.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(34, 'Piscine', 'Envie de construire une piscine ? Je suis votre homme !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(35, 'Piscine', 'J''ai envie d''une piscine pour cet été. Quelqu''un pour me l''installer ?', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(36, 'Plomberie', 'Je suis plombier et je répare vos soucis de tuyauterie en moins de temps qu''il n''en faut pour le dire.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(37, 'Serrurerie', 'Si vous êtes devant votre porte sans pouvoir entrer, faites-moi signe...', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(38, 'Plomberie', 'Mon robinet est cassé. Vite, j''ai besoin d''un plombier !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(39, 'Serrurerie', 'Je suis bloqué devant chez moi sans pouvoir entrer... Y a-t-il un serrurier dans le coin ?', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(40, 'Terrassement', 'Besoin d''un petit terrassement pour la construction de votre nouvelle maison. Je suis dispo !', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(41, 'Terrassement', 'Je construis ma maison et j''ai besoin d''un terrassement. Quelqu''un est-il disponible pour cette tâche ?', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'need'),
(42, 'Alarme & Sécurité', 'Expert en sécurité, je suis à votre écoute pour vous fournir les solutions d''alarmes les plus adaptées à votre environnement.', '2016-02-01 00:00:00', '2016-02-01 00:00:00', 'offer'),
(47, 'Aménagement de cuisine', 'Je recherche un professionnel pour la conception et l''installation d''une cuisine dans ma nouvelle maison.', '2016-02-03 00:00:00', '2016-02-03 00:00:00', 'need'),
(48, 'Isolation', 'Je vis dans un environnement bruyant, et donc je souhaiterais renforcer l''isolation phonique de mon habitat.', '2016-02-03 00:00:00', '2016-02-03 00:00:00', 'need'),
(49, 'Piscine', 'Comme il fait toujours beau en Normandie, j''aimerais construire une piscine dans mon jardin.', '2016-02-03 00:00:00', '2016-02-03 00:00:00', 'need'),
(50, 'Chauffage & Climatisation', 'Il fait froid cet hiver et mon chauffage ne marche plus très bien. Quelqu''un est dispo pour me donner un coup de main ?', '2016-02-03 00:00:00', '2016-02-03 00:00:00', 'need');

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
`id` int(255) NOT NULL,
  `name` varchar(100) NOT NULL,
  `firstname` varchar(100) NOT NULL,
  `description` text,
  `image` varchar(100) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  `passwd` varchar(100) NOT NULL,
  `role` varchar(100) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;

--
-- Contenu de la table `users`
--

INSERT INTO `users` (`id`, `name`, `firstname`, `description`, `image`, `email`, `passwd`, `role`) VALUES
(1, 'Dieng', 'Macky', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at massa ullamcorper, egestas turpis quis, molestie purus. Duis ultrices placerat odio at vehicula. In bibendum sed ipsum ac scelerisque. Morbi et orci sed enim sodales interdum sit amet a lorem. Nam at hendrerit ex. Donec tempor, tellus euismod aliquam laoreet, nisl nulla laoreet eros, quis ullamcorper elit nunc in lacus. Aliquam dignissim erat vel tristique rhoncus. Nunc vel pharetra massa, eleifend rutrum eros. Donec fermentum nisl at magna vehicula fermentum. Integer eget sagittis ex, vitae pharetra urna. Vestibulum posuere sem augue, vitae laoreet justo mollis eget. Aenean vel risus dolor. Vivamus eu suscipit neque, quis suscipit metus. Quisque quis consectetur purus. Suspendisse luctus eget lacus non euismod.\r\n\r\nFusce nec augue at risus facilisis efficitur. Pellentesque rutrum dictum lacinia. Duis sollicitudin id ipsum a ullamcorper. Sed lorem lectus, malesuada nec velit at, vehicula tincidunt mauris. Vestibulum neque enim, volutpat et interdum sed, dapibus at lectus. Mauris egestas maximus orci, eget tincidunt urna venenatis eu. Integer scelerisque eros ut nisl consequat ullamcorper. Praesent ut eros aliquet, cursus ex vel, mattis nibh. Curabitur a nibh quis elit aliquet viverra eu nec elit. Nullam ornare aliquet nisl, ut semper nulla euismod viverra. Curabitur a finibus magna. Nullam vitae tempus felis. Aenean posuere et enim quis sollicitudin. Cras id velit in ex volutpat convallis. Aliquam tincidunt nisi lectus, sit amet vulputate libero dignissim at. ', 'none', 'macky.dieng@gmail.com', '4251c1bf9e22341c792d6f6b02374d50', 'user'),
(2, 'Vannesson', 'Baptiste', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at.\r\n\r\nSuspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', 'none', 'baptiste.vannesson@gmail.com', '05bfed8f89a24f4f46f0edcbd68b83e8', 'admin'),
(3, 'Foucault', 'Julien', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'julien.foucault@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(4, 'Castillo', 'Emiliano', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'emiliano.castillo@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(5, 'Kharaim', 'Mykyta', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'mykyta.kharaim@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(6, 'Maméri', 'Helen', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'helen.mameri@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(7, 'Pelc', 'Laurence', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'laurence.pelc@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(8, 'Brosse', 'Guillaume', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', 'none', 'guillaume.brosse@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(9, 'Le Biez', 'Clément', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'clement.lebiez@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(10, 'Roulet', 'Frantz', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'frantz.roulet@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(11, 'Caillon', 'Yohann', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'yohann.caillon@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(12, 'Lahbib', 'Amani', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'amani.lahbib@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(13, 'Grine', 'Bilal', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'bilal.grine@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(14, 'Rifai', 'Emad', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'emad.rifai@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(15, 'Lebel', 'Antoine', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'antoine.lebel@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(16, 'Tsamba', 'Steeve', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'steeve.tsamba@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(17, 'Belleme', 'Nicolas', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'nicolas.belleme@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(18, 'Artus', 'Kévin', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'kevin.artus@gmail.com', '3dbe00a167653a1aaee01d93e77e730e', 'user'),
(19, 'Zanuttini', 'Bruno', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur convallis, mauris eget dignissim imperdiet, leo arcu interdum sapien, sit amet pellentesque dui urna eget eros. Morbi auctor eget nulla et vulputate. Cras non tortor luctus, accumsan odio at, varius dolor. Ut eu varius mi. Quisque fermentum euismod justo vitae consectetur. Nam faucibus arcu et dui vehicula pellentesque. Aenean viverra turpis quis nulla sodales, vel efficitur arcu semper. Phasellus nulla neque, rhoncus imperdiet pharetra eget, viverra eget tortor. Nullam justo neque, fringilla vitae diam non, sagittis varius justo. Nullam mattis non erat nec porta. Curabitur vulputate dapibus lectus. Praesent finibus, nisl id fermentum gravida, mi massa pretium nisi, sed laoreet felis orci sit amet sem. Duis mollis tellus eu elit maximus, volutpat cursus sem semper. Aliquam euismod volutpat efficitur. Integer id libero eleifend, rutrum justo in, pretium nibh. Curabitur scelerisque nibh mi, at elementum tortor accumsan at. Suspendisse potenti. In dapibus molestie nulla sit amet elementum. Sed nec velit blandit, aliquet lectus quis, ultricies justo. Sed at velit sed nisi malesuada aliquet in eget arcu. Nulla interdum, diam eu convallis finibus, mi mauris fermentum massa, at imperdiet diam eros eget neque. Aliquam nec tortor et tellus auctor luctus. Donec a ultricies sem, ut efficitur libero. Sed tristique pharetra lectus sit amet condimentum. Phasellus interdum ac orci vel blandit. Vestibulum nisi tortor, sagittis quis magna non, faucibus aliquam urna. Praesent cursus elit nec risus scelerisque imperdiet. In tristique augue a lorem auctor, non finibus odio sagittis. Suspendisse id consectetur lacus. Aenean congue augue gravida turpis euismod, id semper velit consequat. ', NULL, 'bruno.zanuttini@unicaen.fr', '61cb37dd915356f70feff321241a9034', 'admin');

-- --------------------------------------------------------

--
-- Structure de la table `user_services`
--

CREATE TABLE IF NOT EXISTS `user_services` (
  `user_id` int(255) NOT NULL,
  `service_id` int(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Contenu de la table `user_services`
--

INSERT INTO `user_services` (`user_id`, `service_id`) VALUES
(1, 1),
(1, 6),
(2, 7),
(2, 8),
(3, 9),
(3, 10),
(4, 11),
(4, 12),
(5, 13),
(5, 14),
(6, 15),
(6, 16),
(7, 17),
(7, 18),
(8, 19),
(8, 20),
(9, 21),
(9, 22),
(10, 23),
(10, 24),
(11, 25),
(11, 26),
(12, 27),
(12, 28),
(13, 29),
(13, 30),
(14, 31),
(14, 32),
(15, 33),
(15, 34),
(16, 35),
(16, 36),
(17, 37),
(17, 38),
(18, 39),
(18, 40),
(19, 41),
(19, 42),
(19, 47),
(19, 48),
(19, 49),
(19, 50);

--
-- Index pour les tables exportées
--

--
-- Index pour la table `services`
--
ALTER TABLE `services`
 ADD PRIMARY KEY (`id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
 ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `services`
--
ALTER TABLE `services`
MODIFY `id` int(255) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=51;
--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
MODIFY `id` int(255) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=21;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
